use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct ProxyConfig {
    pub base_dir: Option<String>,
    pub cert_dir: Option<String>,
    pub local_ui_host: Option<String>,
    pub plugin_host: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub guest_name: Option<String>,
    pub guest_password: Option<String>,
    pub sockets: Option<u32>,
    pub storage: Option<String>,
    pub copy: Option<String>,
    pub dns_cache: Option<u64>,
    pub host: Option<String>,
    pub port: Option<u16>,
    pub uiport: Option<u16>,
    pub middlewares: Option<String>,
    pub mode: Option<String>,
    pub timeout: Option<u64>,
    pub extra: Option<String>,
    pub secure_filter: Option<String>,
    pub shadow_rules: Option<String>,
    pub req_cache_size: Option<u32>,
    pub frame_cache_size: Option<u32>,
    pub addon: Option<String>,
    pub init: Option<bool>,
    pub cluster: Option<u16>,
    pub dns_server: Option<String>,
    pub socks_port: Option<u16>,
    pub http_port: Option<u16>,
    pub https_port: Option<u16>,
    pub allow_origin: Option<String>,
    pub global_plugins: Option<bool>,
    pub prev_options: Option<bool>,
    pub inspect: Option<String>,
    pub inspect_brk: Option<String>,
}

impl Default for ProxyConfig {
    fn default() -> Self {
        Self {
            base_dir: None,
            cert_dir: None,
            local_ui_host: Some("local.whistlejs.com".into()),
            plugin_host: None,
            username: None,
            password: None,
            guest_name: None,
            guest_password: None,
            sockets: Some(60),
            storage: None,
            copy: None,
            dns_cache: Some(60000),
            host: Some("0.0.0.0".into()),
            port: Some(8899),
            uiport: Some(8898),
            middlewares: None,
            mode: None,
            timeout: Some(60000),
            extra: None,
            secure_filter: None,
            shadow_rules: None,
            req_cache_size: Some(600),
            frame_cache_size: Some(512),
            addon: None,
            init: Some(false),
            cluster: Some(0),
            dns_server: None,
            socks_port: Some(1080),
            http_port: Some(8080),
            https_port: Some(8443),
            allow_origin: None,
            global_plugins: Some(true),
            prev_options: Some(true),
            inspect: None,
            inspect_brk: None,
        }
    }
}
